# {build} is required by AppVeyor to uniquely identify its builds on the url
# It is a continuously incrementing number so when used it violates the reset
# smaller build parts rule of semantic versioning. Therefore we introduce a
# second environment variable semantic_version.
# Until a newer version of dotnet/nuget sdk is released (currently 1.0.4)
# Also need to set version number in Redo/Redo.nuspec file.
version: 0.6.0.{build}

image: Visual Studio 2017

environment:
  RunCodeAnalysis: false

configuration:
  - Debug
  - Release

cache:
  - packages -> **\packages.config

install:
  - set semantic_version=%APPVEYOR_BUILD_VERSION:~0,5%
  - echo Version - %semantic_version%
  - dotnet restore

nuget:
  disable_publish_on_pr: true

assembly_info:
  patch: false
  file: '**\AssemblyInfo.*'
  assembly_version: '$(semantic_version).{build}'
  assembly_file_version: '$(semantic_version).{build}'
  assembly_informational_version: '$(semantic_version)'

build:
  parallel: true
  verbosity: normal

test_script:
  - cmd: dotnet test

deploy:
  - provider: NuGet
    on:
      branch: donotpublish-master
      configuration: Release
    api_key:
      secure: dUMLXnYuqF7ORswtDCtj2XgKlpLMKrXZrq9m/FEN2xu0vTClejXqADyxMEawTs2W
    skip_symbols: true
    artifact: /.*\.nupkg/
