version: 0.1.{build}

configuration:
  - Debug
  - Release

install:
  - nuget restore

nuget:
  disable_publish_on_pr: true

build:
  publish_nuget: true
  parallel: true
  verbosity: normal

artifacts:
  - path: Redo\bin\Debug
  - path: Redo\bin\Release